### PR TITLE
show future commit dates without panicking

### LINKED ISSUE #1306: Handle future commit datetimes in the future without panicking
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

If the commit time is in the future, onefetch crashes.

### Expected behavior 🤔

It should possibly handle the case or fail gracefully. The crash report blames this on me, but my system time is okay and I don't have much influence over my colleague's system time.

### Steps to reproduce 🕹

Have the most recent git commit in the future and run `onefetch`

### Additional context/Screenshots 🔦

```
name = "onefetch"
operating_system = "NixOS 24.5.0 [64-bit]"
crate_version = "2.20.0"
explanation = """
Panic occurred in file 'src/info/utils/mod.rs' at line 35
"""
cause = "Achievement unlocked: time travel! Check your system clock and commit dates."
method = "Panic"
backtrace = """

   0: 0x56049cc6bb63 - core::option::expect_failed::hcbf5a9b7e22cab9f
   1: 0x56049cc93285 - onefetch::info::utils::format_time::he784b32eb1d439c7
   2: 0x56049ccec879 - onefetch::info::InfoBuilder::last_change::h5aac04e9a53655fa
   3: 0x56049ccea471 - onefetch::info::build_info::h6232c8d9e8572b77
   4: 0x56049cc7dded - onefetch::main::hfc8e895e84fac4d0
   5: 0x56049cc85363 - std::sys_common::backtrace::__rust_begin_short_backtrace::he043df6535079d0d
   6: 0x56049cc86c9d - std::rt::lang_start::{{closure}}::h5f878ceb72151ea0
   7: 0x56049d5883d4 - std::panicking::try::h45c8379f4866ecc7
   8: 0x56049d581eb5 - std::rt::lang_start_internal::hf358ddc7f05da9a0
   9: 0x56049cc7e5f5 - main
  10: 0x7f25f061c0ce - __libc_start_call_main
  11: 0x7f25f061c189 - __libc_start_main@GLIBC_2.2.5
  12: 0x56049cc6be25 - _start
  13:        0x0 - <unresolved>"""
```

### Possible Solution 💡

_No response_

Thanks for your awesome work!

### PR DESCRIPTION
**Pull request by MalteT**
Fixes #1306.

Sorry for the long wait! This is the lamest solution I found, the tool will simply display the time as `in 5 days`. The library `time_humanize` can already handle this.

Thanks!

### CODE REVIEW

**Review by spenserblack — APPROVED** [review]
The simplest solution is often the best. I think saying that the repo is created "in x days/hours/etc." is an elegant and clear way to call out a time traveler.

Is there an emoji combo that can represent a time traveler? :thinking:

File: src/info/utils/mod.rs [hunk 1]
```diff
@@ -27,16 +27,14 @@ fn to_human_time(time: Time) -> String {
...
-    let duration = since_epoch_duration.checked_sub(ts).expect(
-        "Achievement unlocked: time travel! \
-        Check your system clock and commit dates.",
-    );
-    let ht = HumanTime::from(-(duration.as_secs() as i64));
+    // Calculate the distance from the current time. This handles
+    // future dates gracefully and will simply return something like `in 5 minutes`
+    let duration = (ts.as_secs() as i64) - (since_epoch_duration.as_secs() as i64);
+    let ht = HumanTime::from(duration);
     ht.to_string()
```
Comment (o2sh) [inline src/info/utils/mod.rs:38]: Here is a suggestion to simplify the logic and handle commit time before epoch :
```rust
fn to_human_time(time: Time) -> String {
    let since_epoch_duration = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .expect("System time is before the Unix epoch");

    // Calculate the distance from the current time. This handles
    // future dates gracefully and will simply return something like `in 5 minutes`
    let delta_in_seconds = time.seconds - (since_epoch_duration.as_secs() as i64);
    HumanTime::from(delta_in_seconds).to_string()
}
```
It will also require to update the unit test `display_time_before_epoch` to avoid an underflow

**Comment by MalteT** [comment]
> The simplest solution is often the best. I think saying that the repo is created "in x days/hours/etc." is an elegant and clear way to call out a time traveler.
> 
> Is there an emoji combo that can represent a time traveler? 🤔

🕰️🚀

Maybe those? Did you plan on having something like this?
image

**Comment by spenserblack** [comment]
That emoji combo looks good! I'm not saying we have to add those, I was kind of half-joking. But it could be fun as an easter egg.

**Review by o2sh — APPROVED** [review]

**Review by o2sh — APPROVED** [review]
I think we can leave out the emoji for now 🤔 

Thanks a lot for you contribution @MalteT and @spenserblack for the review 🎉

**Comment by MalteT** [comment]
> I think we can leave out the emoji for now 🤔

Depending on the requirements (is there a config option for emojis? would we always show the with the message?) I would be willing to open a mini PR to add that, @o2sh 🤔

**Comment by spenserblack** [comment]
> is there a config option for emojis?

Nope, because we don't have any emojis in the output yet.
