### PR TITLE
worktree support via gitoxide 0.17 (up from 0.16)

### LINKED ISSUE #651: Upcoming v2.13 doesn't work at all with worktrees
This is due to `gitoxide` currently not handling them at all.

In the example below, `onefetch` is the latest build from `main` whereas `onefetch-pre-gitoxide` is the one using `git2`.
```
➜  gitoxide.worktree git:(gitoxide.worktree) onefetch
Error: Could not find a valid HEAD reference

Caused by:
    The ref partially named 'HEAD' could not be found
➜  gitoxide.worktree git:(gitoxide.worktree) onefetch-pre-gitoxide
                 R RR RR                  Sebastian Thiel ~ git version 2.32.0 (Apple Git-132)
              R RRRRRRRR R          R     ----------------------------------------------------
 R RR       R RRRRRRRRRRRRR R      RR     Project: gitoxide (455 tags)
rR RRR    R RRRRRRRRRRRRRRRRR R   RRR R   HEAD: df8fe68 (gitoxide.worktree, worktree-stack)
RRR RR   RRRRRRRRRRRRRRRRRRRRRRR  RRRRR   Version: git-sequencer-v0.0.0
 RRRRR  RRRRRRRRRRRRRRRRRRRRRRRR  RRRR    Created: 3 years ago
  RRR RRRRRRRRRRRRRRRRRRRRRRRRRRRR RR     Languages:
    R  RRRRRRRRRR=  RR = RRRRRRRRRRR                 ● Rust (96.9 %) ● Shell (3.1 %)
     RRRRRRRRRRRR=  RR = RRRRRRRRRR       Dependencies: 12 (cargo)
      RRRRRRRRRRR   RR   RRRRRRRRRR       Authors: 95% Sebastian Thiel 6398
     RR==RRRRRRRRRRRRRRRRRRRRRR===RR               2% Edward Shen 147
     RR =  ==RRRRRRR  RRRRRR==  = RR               0% Conor Davis 33
      RR =     ===========     = RR       Last change: 7 minutes ago
       RR                        R        Contributors: 30
        R                       R         Repo: /Users/byron/dev/github.com/Byron/gitoxide
         R                                Commits: 6715
                                          Lines of code: 75163
                                          Size: 6.37 MiB (1212 files)
                                          License: Apache-2.0, MIT



➜  gitoxide.worktree git:(gitoxide.worktree)
```

I'd consider this a blocker for the v2.13 release and will implement basic support for this next.

### PR DESCRIPTION
**Pull request by Byron**
Fixes #651 .

### CODE REVIEW

File: src/info/repo.rs [hunk 1]
```diff
@@ -155,7 +155,7 @@ impl Commits {
 
 impl Repo {
     pub fn new(git2_repo: Repository) -> Result<Self> {
-        let repo = git::open(git2_repo.path())?;
+        let repo = git::open(git2_repo.workdir().unwrap_or(git2_repo.path()))?;
```
Comment (spenserblack) [inline src/info/repo.rs:158]: As a quick double-check, looks like `.workdir()` only returns `None` if the repository is bare. So effectively this attempts to open either the workdir path or the path to the bare repository, right? Just checking that that's wanted.

**Review by spenserblack — APPROVED** [review]
Overall LGTM! Just a note for a quick double-check.

File: src/info/repo.rs (hunk 1 above)
Comment (Byron) [reply src/info/repo.rs:158]: That's a great catch! Actually this was a workaround to `gitoxide` being unable to open `.git/worktrees/<name>` paths at the time, which has since been fixed. So I rolled it back to `git2_repo.path()` exactly like before.

As a side-note, while implementing worktree support it became clear that I have to change my thinking about what `bare` really means. In short: don't assume that `bare` repositories have no worktree. In fact, they can have several _linked_ worktrees via `git worktree`. The only way to know if there is a worktree is to open a repository and checking for the presence of a `work_dir()`. Oh, to make things more fun: this directory might not even exist as it's just something pointed to by a file that we didn't have to touch yet (and which is exactly what can happen if a repo is opened through `.git/worktrees/<name>`.
